project:
  type: website
  output-dir: docs

website:
  title: "Simon Herrmann"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: blog/index.qmd
        text: Blog
      - href: cv/index.qmd
        text: CV
      - href: publications.qmd
        text: Publications

format:
  html:
    theme:
    - html/template.scss
    toc: true
    reference-location: margin
    footnotes-hover: true