project:
  type: website
  output-dir: docs

website:
  title: "Simon Herrmann"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: blog/index.qmd
        text: Blog
      - href: cv/index.qmd
        text: CV
      - href: publications.qmd
        text: Publications

format:
  html:
    theme:
    - html/template.scss
    toc: true




# Metadata 
#pagetitle: "{{< meta title >}} | Andrew Heiss"
#author-meta: "Andrew Heiss"

#website:
#  title: "Andrew Heiss"
#  description: "Andrew Heiss is an assistant professor at Georgia State University, researching international NGOs and teaching data science & economics."
#  favicon: "/files/favicon-512.png"
#  site-url: "https://www.andrewheiss.com"